name: CI/CD Pipeline for Invoice Generator

# Trigger the pipeline on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Step 4: Build and Tag Docker Image
      - name: Build and tag the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/invoice-generator:latest .

      # Step 5: Push the Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/invoice-generator:latest

      # Step 6: SSH into the DigitalOcean server and deploy the Docker image
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DIGITALOCEAN_SERVER_IP }}
          username: ${{ secrets.DIGITALOCEAN_SERVER_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/invoice-generator:latest
            docker stop invoice-generator || true
            docker rm invoice-generator || true
            docker run -d -p 80:80 --name invoice-generator ${{ secrets.DOCKERHUB_USERNAME }}/invoice-generator:latest
